# Generated by Django 3.1.2 on 2020-10-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmpId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('emailID', models.EmailField(blank=True, max_length=254, null=True)),
                ('contactNo', models.CharField(blank=True, max_length=12, null=True)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=64)),
                ('product_quantity', models.IntegerField()),
                ('product_prize', models.CharField(max_length=64)),
            ],
        ),
    ]
